"""Generate tokens.css from palette.json and check the intended contrast pairs.

Run from any directory: python3 assets/design/build_tokens.py
No dependencies. This checks color pairs, not full application accessibility.
"""

import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
palette = json.loads((ROOT / "palette.json").read_text())
colors = palette["colors"]
for name, value in colors.items():
    if not re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
        raise ValueError(f"Invalid sRGB color: {name} = {value}")


def luminance(hex_color):
    channels = [int(hex_color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [v / 12.92 if v <= 0.04045 else ((v + .055) / 1.055) ** 2.4 for v in channels]
    return sum(v * w for v, w in zip(linear, (.2126, .7152, .0722)))


def contrast(first, second):
    high, low = sorted((luminance(colors[first]), luminance(colors[second])), reverse=True)
    return (high + .05) / (low + .05)


pairs = [(fg, bg, 4.5) for fg in ("text", "text-secondary", "text-muted")
         for bg in ("canvas", "sidebar", "surface", "raised", "hover", "selected")]
pairs += [("on-accent", bg, 4.5) for bg in ("accent", "accent-hover")]
pairs += [(state, state + "-bg", 4.5) for state in ("success", "warning", "danger", "info")]
pairs += [(fg, bg, 3) for fg in ("focus", "control-border")
          for bg in ("canvas", "sidebar", "surface", "raised")]
for fg, bg, minimum in pairs:
    ratio = contrast(fg, bg)
    if ratio < minimum:
        raise ValueError(f"Contrast {fg}/{bg}: {ratio:.2f}:1 < {minimum}:1")

lines = ["/* Generated by build_tokens.py. Edit palette.json, then regenerate. */",
         ":root, .dark, [data-theme=\"regulus-dark\"] {", "  color-scheme: dark;"]
for group in ("colors", "font", "radius", "space", "duration", "ease", "shadow", "gradient", "chart", "layout"):
    prefix = "color" if group == "colors" else group
    for name, value in palette[group].items():
        lines.append(f"  --rg-{prefix}-{name}: {value};")
lines.append("}")
lines.extend(["", "@media (prefers-reduced-motion: reduce) {",
              "  :root, .dark, [data-theme=\"regulus-dark\"] {",
              "    --rg-duration-fast: 0ms;", "    --rg-duration-normal: 0ms;", "  }", "}", ""])
(ROOT / "tokens.css").write_text("\n".join(lines))
print(f"Generated tokens.css; {len(pairs)} contrast pairs passed.")
for fg, bg in [("text", "canvas"), ("text-muted", "raised"),
               ("on-accent", "accent"), ("control-border", "raised")]:
    print(f"  {fg} / {bg}: {contrast(fg, bg):.2f}:1")
